### ISSUE TITLE
设置了pageDotImage、currentPageDotImage后会crash：[UIView setImage:]

### ISSUE THREAD

**Issue by maxhis** [gsdios/SDCycleScrollView#131]
去掉设置pageDotImage、currentPageDotImage就正常了，使用的swift开发。具体出错信息如下：

 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView setImage:]: unrecognized selector sent to instance 0x7faebb8523e0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000108148e65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000107896deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010815148d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010809e90a ___forwarding___ + 970
	4   CoreFoundation                      0x000000010809e4b8 _CF_forwarding_prep_0 + 120
	5   UIKit                               0x0000000108e4d921 -[UIPageControl _transitionIndicator:toEnabled:index:legible:] + 140
	6   UIKit                               0x0000000108e4d9b5 -[UIPageControl _transitionIndicator:toEnabled:index:] + 82
	7   UIKit                               0x0000000108e4d64e -[UIPageControl _setDisplayedPage:] + 123
	8   UIKit                               0x000000011b0ec267 -[UIPageControlAccessibility setCurrentPage:] + 93
	9   SDCycleScrollView                   0x00000001072b45fb -[SDCycleScrollView scrollViewDidScroll:] + 731
	10  UIKit                               0x0000000108bd34e4 -[UIScrollView(UIScrollViewInternal) _notifyDidScroll] + 66
	11  UIKit                               0x000000011b0daa50 -[UIScrollViewAccessibility _notifyDidScroll] + 39
	12  UIKit                               0x0000000108bbf3b6 -[UIScrollView setContentOffset:] + 651
	13  UIKit                               0x0000000108bb9223 -[UIScrollViewScrollAnimation setProgress:] + 406
	14  UIKit                               0x0000000108c729d6 -[UIAnimator(Static) _advanceAnimationsOfType:withTimestamp:] + 207
	15  QuartzCore                          0x00000001089dba8c _ZN2CA7Display15DisplayLinkItem8dispatchEv + 50
	16  QuartzCore                          0x00000001089db956 _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 418
	17  CoreFoundation                      0x00000001080a8c84 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	18  CoreFoundation                      0x00000001080a8831 __CFRunLoopDoTimer + 1089
	19  CoreFoundation                      0x000000010806a241 __CFRunLoopRun + 1937
	20  CoreFoundation                      0x0000000108069828 CFRunLoopRunSpecific + 488
	21  GraphicsServices                    0x000000010eb1aad2 GSEventRunModal + 161
	22  UIKit                               0x0000000108afa610 UIApplicationMain + 171
	23  Meika                               0x00000001067517dd main + 109
	24  libdyld.dylib                       0x000000010b46c92d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by maxhis** [comment]
Has it been fixed?

**Comment by Airwen** [comment]
I also met the same problem,i'm use SDCycleScrollView in tablecell，do you  fix it 

`

2017-05-22 10:45:12.183476 Project[15918:5826756] Setting the background color on UITableViewHeaderFooterView has been deprecated. Please use contentView.backgroundColor instead.
2017-05-22 10:45:13.222094 Project[15918:5826756] [Assert] negative or zero item sizes are not supported in the flow layout
2017-05-22 10:45:26.802179 Project[15918:5826756] -[SDCycleScrollView setCurrentPageDotColor:]: unrecognized selector sent to instance 0xe560ed0
2017-05-22 10:45:26.813907 Project[15918:5826756] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SDCycleScrollView setCurrentPageDotColor:]: unrecognized selector sent to instance 0xe560ed0'
*** First throw call stack:
(0x1d0ecdf7 0x1c34f077 0x1d0f2505 0x1d0f0579 0x1d0153d8 0x25cbd5 0x222d8243 0x20b429 0x224d01f7 0x224d1765 0x221a6713 0x224d15d5 0x224d1e61 0x22286a5d 0x224bef85 0x224d74c1 0x2227c9f5 0x22195dad 0x1ffa9841 0x1ff9d78f 0x1ff9d61f 0x1ff2e2c3 0x1ff4cbb5 0x1ff4d653 0x1d0a7f15 0x1d0a6191 0x1d0a65a7 0x1cff5533 0x1cff5341 0x1e7ccbfd 0x22203e67 0x221fe591 0x27d22b 0x1c7bf50b)
libc++abi.dylib: terminating with uncaught exception of type NSException
`

**Comment by maxhis** [comment]
@Airwen Yes, just update to the latest version.
