### ISSUE TITLE
sdwebImage 为啥要使用4.0.0 之后版本？

### ISSUE THREAD

**Issue by brave723** [gsdios/SDCycleScrollView#423]
sdwebImage 为啥要使用4.0.0 之后版本？3.7版本也不会有问题吧！

**Comment by dragontianxia** [comment]
FYI.

About SDWebImage.

> 4.1 patch
@bpoplauschi bpoplauschi released this on Oct 7 · 66 commits to master since this release

See all tickets marked for the 4.1.1 release

Fixes

Fixed crash on [SDWebImageDownloaderOperation reset]_block_invoke 2f892f9 fixes #1883
Fixed SDWebImageDownloadOperation imageData multi-thread issue #2011 fixes #1998 [SDWebImageDownloaderOperation URLSession:dataTask:didReceiveData:] crash
Fixed CFRelease on NULL if CGImageSourceRef create failed #1978 fixes #1968 #1834 #1947
Fixed request cache policy #1994 #2032 fixes #1993 #1861 #1623 was introduced by #1737 (unit test #2031)
Fixed CGBitmapContextCreate bitmap memory leak #1976 replaces #1860 fixes #1974
Fixed issue #2001, add sd_currentBackgroundImageURL and sd_backgroundImageURLForState: for UIButton #2002
Set UIButton placeholer-image even if the url is nil #2043 fixes #1721 #1964 replaces #1790
Use CGImageSourceCreateIncremental to perform progressive decoding instead of decode partial data each time from the beginning to improve performance and remove that gray background #2040 fixes #1899
Fix SDWebImage v4 can not import libwebp framework's header files #1983 fixes #1887
Fix unreachable code build warning on macOS #1984

**但是 SDCycleScrollView 的作者为什么在 ReadMe 写了 更新对SDWebImage 的依赖，但实际还是依赖于4.0.0 呢？只更新了 ReadMe ？？？**
